spring:
  cloud:
    consul:
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-interval: 5s
        health-check-timeout: 10s
        health-check-critical-timeout: 10s
        deregister_critical_service_after: 1m
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics