spring:
  cloud:
    consul:
      host: consul-server
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${random.uuid}
        health-check-interval: 15s
        health-check-timeout: 60s
        health-check-critical-timeout: 2m
        prefer-ip-address: true
  zipkin:
    baseUrl: http://zipkin:9411/

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics