spring:
  cloud:
      consul:
        host: localhost
        port: 8500
        discovery:
          service-name: ${spring.application.name}
          instance-id: ${spring.application.name}:${random.uuid}
          healthCheckPath: /actuator/health
          healthCheckInterval: 15s
          healthCheckTimeout: 60s
          healthCheckCriticalTimeout: 5m
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - beans
          - mappings
          - metrics