server:
  port: 8181
spring:
  cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /