server:
  port: 8383
spring:
  datasource:
    url: jdbc:mysql://dbprogrammation:3306/gestioncinema_programmation
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
feign:
  client:
    config:
      film-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
      cinema-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
  # cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
    # stream:
    #   binders:
    #     rabbit:
    #       type: rabbit
    #       environment:
    #         spring:
    #           rabbitmq:
    #             host: localhost
    #             port: 5672
    #             username: guest
    #             password: guest
    #             virtual-host: /