server:
  port: 8383
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestioncinema_programmation
  jpa:
    hibernate:
      ddl-auto: create-drop
  cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /