server:
  port: 8484
spring:
  datasource:
    url: jdbc:mysql://dbreservation:3306/gestioncinema_reservation
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
  #   consul:
  #     host: localhost
  #     port: 8500
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest
                virtual-host: /