server:
  port: 8585

application:
  jwt:
    secret: "m0N_Sup3R_C0d3_S3creT"
    expires: 86400000
    prefix: "Bearer "
    header: "Authorization"
spring:
  datasource:
    url: jdbc:mysql://dbuser:3306/gestioncinema_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  zipkin:
    baseUrl: http://zipkin:9411/
  cloud:
    consul:
      host: consul-server
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: rabbitmq
                port: 5672
                username: guest
                password: guest
                virtual-host: /
